services:
  bot:
    build: .
    container_name: tg_media_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - INTERVAL_MINUTES=${INTERVAL_MINUTES}
      - ALLOWED_USER_ID=${ALLOWED_USER_ID}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - DB_PATH=/app/data/posts.db
    volumes:
      - ./:/app   # монтируем весь проект, чтобы код моментально обновлялся
      - ./data:/app/data
